
import { User, Post, Clan, UserRole, Story } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'admin_kerri',
    name: 'Kerri',
    handle: '@kerri',
    email: 'kerri@nexes.com',
    password: 'Fastgan56',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kerri&backgroundColor=b6e3f4',
    coverImage: '#4f46e5',
    bio: 'Platform Administrator & Community Manager.',
    location: 'Nexes HQ',
    role: UserRole.ADMIN,
    followers: 0,
    following: 0,
    followingIds: [],
    belledUserIds: [],
    joinedAt: new Date().toISOString(),
    isPrivate: false,
    status: { text: "Building Nexes", emoji: "🚀" }
  }
];

export const MOCK_CLANS: Clan[] = [];

export const MOCK_POSTS: Post[] = [];

export const MOCK_STORIES: Story[] = [];

export const TRANSLATIONS = {
  en: {
    nav_feed: "News Feed",
    nav_search: "Search",
    nav_notifs: "Notifications",
    nav_profile: "My Profile",
    nav_clans: "Clans",
    nav_messages: "Messages",
    nav_admin: "Admin Panel",
    nav_settings: "Settings",
    nav_signout: "Sign Out",
    welcome: "Welcome to Nexes",
    login_subtitle: "Connect via UZU or Email.",
    signin: "Sign In",
    signup: "Create Account",
    search: "Search...",
    post_placeholder: "What's on your mind?",
    post_btn: "Post",
    photo: "Media",
    ai_enhance: "AI Enhance",
    settings_title: "Account Settings",
    lang_title: "Language",
    breathing_title: "Wave Background",
    privacy_title: "Private Account",
    security_title: "Security",
    save: "Save Changes",
    edit_profile: "Edit Profile",
    followers: "Followers",
    following: "Following",
    join_clan: "Join Clan",
    create_clan: "Create Clan",
    members: "Members",
    admin_dashboard: "Admin Dashboard",
    banned: "Banned",
    delete: "Delete",
    view_details: "View Details",
    comments: "Comments",
    liked: "liked your post",
    commented: "commented on your post",
    followed: "started following you",
    invited: "invited you to join",
    stats_posts: "Total Posts",
    stats_comments: "Comments Made",
    stats_likes: "Likes Given",
    stats_clans: "Clans Joined",
    edit_post: "Edit Post",
    cancel: "Cancel",
    save_post: "Save",
    invite_members: "Invite Members",
    invite: "Invite",
    about: "About",
    community_board: "Community Board",
    send_message: "Send Message",
    share_to: "Share to Friend"
  },
  ru: {
    nav_feed: "Лента",
    nav_search: "Поиск",
    nav_notifs: "Уведомления",
    nav_profile: "Профиль",
    nav_clans: "Кланы",
    nav_messages: "Сообщения",
    nav_admin: "Админка",
    nav_settings: "Настройки",
    nav_signout: "Выйти",
    welcome: "Добро пожаловать в Nexes",
    login_subtitle: "Войдите через UZU или Email.",
    signin: "Войти",
    signup: "Регистрация",
    search: "Поиск...",
    post_placeholder: "О чем вы думаете?",
    post_btn: "Опубликовать",
    photo: "Медиа",
    ai_enhance: "AI-улучшение",
    settings_title: "Настройки аккаунта",
    lang_title: "Язык",
    breathing_title: "Волновой фон",
    privacy_title: "Закрытый аккаунт",
    security_title: "Безопасность",
    save: "Сохранить",
    edit_profile: "Редактировать",
    followers: "Подписчики",
    following: "Подписки",
    join_clan: "Вступить",
    create_clan: "Создать клан",
    members: "Участники",
    admin_dashboard: "Панель управления",
    banned: "Забанен",
    delete: "Удалить",
    view_details: "Подробнее",
    comments: "Комментарии",
    liked: "понравилась ваша запись",
    commented: "прокомментировал",
    followed: "подписался на вас",
    invited: "пригласил вас в",
    stats_posts: "Посты",
    stats_comments: "Комменты",
    stats_likes: "Лайки",
    stats_clans: "Кланы",
    edit_post: "Изменить",
    cancel: "Отмена",
    save_post: "Сохранить",
    invite_members: "Пригласить",
    invite: "Пригласить",
    about: "О нас",
    community_board: "Стена",
    send_message: "Отправить сообщение",
    share_to: "Поделиться"
  },
  es: {
    nav_feed: "Noticias",
    nav_search: "Buscar",
    nav_notifs: "Notificaciones",
    nav_profile: "Mi Perfil",
    nav_clans: "Clanes",
    nav_messages: "Mensajes",
    nav_admin: "Panel de Admin",
    nav_settings: "Ajustes",
    nav_signout: "Cerrar Sesión",
    welcome: "Bienvenido a Nexes",
    login_subtitle: "Conéctate vía UZU o Email.",
    signin: "Iniciar Sesión",
    signup: "Registrarse",
    search: "Buscar...",
    post_placeholder: "¿Qué estás pensando?",
    post_btn: "Publicar",
    photo: "Media",
    ai_enhance: "Mejora IA",
    settings_title: "Ajustes de Cuenta",
    lang_title: "Idioma",
    breathing_title: "Fondo de Olas",
    privacy_title: "Cuenta Privada",
    security_title: "Seguridad",
    save: "Guardar Cambios",
    edit_profile: "Editar Perfil",
    followers: "Seguidores",
    following: "Siguiendo",
    join_clan: "Unirse al Clan",
    create_clan: "Crear Clan",
    members: "Miembros",
    admin_dashboard: "Panel de Control",
    banned: "Baneado",
    delete: "Eliminar",
    view_details: "Ver Detalles",
    comments: "Comentarios",
    liked: "le gustó tu publicación",
    commented: "comentó en tu publicación",
    followed: "comenzó a seguirte",
    invited: "te invitó a unirte",
    stats_posts: "Publicaciones",
    stats_comments: "Comentarios",
    stats_likes: "Me gusta dados",
    stats_clans: "Clanes",
    edit_post: "Editar",
    cancel: "Cancelar",
    save_post: "Guardar",
    invite_members: "Invitar Miembros",
    invite: "Invitar",
    about: "Acerca de",
    community_board: "Tablero Comunitario",
    send_message: "Enviar Mensaje",
    share_to: "Compartir"
  },
  fr: {
    nav_feed: "Fil d'actualité",
    nav_search: "Recherche",
    nav_notifs: "Notifications",
    nav_profile: "Mon Profil",
    nav_clans: "Clans",
    nav_messages: "Messages",
    nav_admin: "Admin",
    nav_settings: "Paramètres",
    nav_signout: "Déconnexion",
    welcome: "Bienvenue sur Nexes",
    login_subtitle: "Connectez-vous via UZU ou Email.",
    signin: "Se connecter",
    signup: "Créer un compte",
    search: "Rechercher...",
    post_placeholder: "Quoi de neuf ?",
    post_btn: "Publier",
    photo: "Média",
    ai_enhance: "IA Améliorer",
    settings_title: "Paramètres du compte",
    lang_title: "Langue",
    breathing_title: "Fond Vagues",
    privacy_title: "Compte privé",
    security_title: "Sécurité",
    save: "Enregistrer",
    edit_profile: "Modifier le profil",
    followers: "Abonnés",
    following: "Abonnements",
    join_clan: "Rejoindre le clan",
    create_clan: "Créer un clan",
    members: "Membres",
    admin_dashboard: "Tableau de bord",
    banned: "Banni",
    delete: "Supprimer",
    view_details: "Voir les détails",
    comments: "Commentaires",
    liked: "a aimé votre post",
    commented: "a commenté votre post",
    followed: "a commencé à vous suivre",
    invited: "vous a invité à rejoindre",
    stats_posts: "Posts",
    stats_comments: "Commentaires",
    stats_likes: "J'aime donnés",
    stats_clans: "Clans",
    edit_post: "Modifier",
    cancel: "Annuler",
    save_post: "Sauver",
    invite_members: "Inviter",
    invite: "Inviter",
    about: "À propos",
    community_board: "Mur communautaire",
    send_message: "Envoyer un message",
    share_to: "Partager"
  },
  de: {
    nav_feed: "News Feed",
    nav_search: "Suche",
    nav_notifs: "Benachrichtigungen",
    nav_profile: "Mein Profil",
    nav_clans: "Clans",
    nav_messages: "Nachrichten",
    nav_admin: "Admin-Panel",
    nav_settings: "Einstellungen",
    nav_signout: "Abmelden",
    welcome: "Willkommen bei Nexes",
    login_subtitle: "Verbinden via UZU oder E-Mail.",
    signin: "Anmelden",
    signup: "Konto erstellen",
    search: "Suchen...",
    post_placeholder: "Was machst du gerade?",
    post_btn: "Posten",
    photo: "Medien",
    ai_enhance: "KI-Verbesserung",
    settings_title: "Kontoeinstellungen",
    lang_title: "Sprache",
    breathing_title: "Wellen-Hintergrund",
    privacy_title: "Privates Konto",
    security_title: "Sicherheit",
    save: "Änderungen speichern",
    edit_profile: "Profil bearbeiten",
    followers: "Follower",
    following: "Gefolgt",
    join_clan: "Clan beitreten",
    create_clan: "Clan erstellen",
    members: "Mitglieder",
    admin_dashboard: "Admin-Dashboard",
    banned: "Verbannt",
    delete: "Löschen",
    view_details: "Details anzeigen",
    comments: "Kommentare",
    liked: "gefällt dein Beitrag",
    commented: "hat deinen Beitrag kommentiert",
    followed: "folgt dir jetzt",
    invited: "hat dich eingeladen",
    stats_posts: "Beiträge",
    stats_comments: "Kommentare",
    stats_likes: "Likes vergeben",
    stats_clans: "Clans",
    edit_post: "Bearbeiten",
    cancel: "Abbrechen",
    save_post: "Speichern",
    invite_members: "Einladen",
    invite: "Einladen",
    about: "Über",
    community_board: "Community Board",
    send_message: "Nachricht senden",
    share_to: "Teilen"
  },
  ja: {
    nav_feed: "ニュースフィード",
    nav_search: "検索",
    nav_notifs: "通知",
    nav_profile: "プロフィール",
    nav_clans: "クラン",
    nav_messages: "メッセージ",
    nav_admin: "管理パネル",
    nav_settings: "設定",
    nav_signout: "ログアウト",
    welcome: "Nexesへようこそ",
    login_subtitle: "UZUまたはメールで接続",
    signin: "ログイン",
    signup: "アカウント作成",
    search: "検索...",
    post_placeholder: "何を考えていますか？",
    post_btn: "投稿",
    photo: "メディア",
    ai_enhance: "AI強化",
    settings_title: "アカウント設定",
    lang_title: "言語",
    breathing_title: "ウェーブ背景",
    privacy_title: "非公開アカウント",
    security_title: "セキュリティ",
    save: "変更を保存",
    edit_profile: "プロフィール編集",
    followers: "フォロワー",
    following: "フォロー中",
    join_clan: "クランに参加",
    create_clan: "クラン作成",
    members: "メンバー",
    admin_dashboard: "管理ダッシュボード",
    banned: "禁止",
    delete: "削除",
    view_details: "詳細を見る",
    comments: "コメント",
    liked: "が「いいね」しました",
    commented: "がコメントしました",
    followed: "がフォローしました",
    invited: "が招待しました",
    stats_posts: "投稿",
    stats_comments: "コメント",
    stats_likes: "いいね数",
    stats_clans: "参加クラン",
    edit_post: "編集",
    cancel: "キャンセル",
    save_post: "保存",
    invite_members: "招待",
    invite: "招待",
    about: "詳細",
    community_board: "コミュニティボード",
    send_message: "メッセージ送信",
    share_to: "共有"
  }
};